### ISSUE TITLE
Does hyde code exist?

### ISSUE THREAD

**Issue by sci-phi** [hydecr/hyde-blog#1]
Was looking for an alternative to Jekyll or Hugo in Crystal, and this seems perfect... except that the shard does not work and nothing but skeleton code in the repos on github. The documentation looks promising, as if there is a real working implementation somewhere...

Am I missing something fundamental? How do I use hyde & hyde-blog?

**Comment by watzon** [comment]
This project is a WIP, I ended up getting sidetracked with other projects and my job so I haven't worked on it in a bit. It's not actually ready to go though.
